# Aula de build
#
# docker image build -t first-build .
#  *       *     *    1      2      3
#
# 1 = flag para nomear a imagem
# 2 = nome da imagem
# 3 = diretório onde se encontra o Dockerfile

FROM nginx:latest
RUN echo '<h1> Hello World from Docker!' > /usr/share/nginx/html/index.html